//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 210.149954 on Stable branch
// Generated with ALiVE version 1.17.0.2209061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class HS_SCP_Fac {
        displayName = "SCP Foundation";
        side = 1;
        flag = "\HS_UI_FN\Map\Markers\Flags\scp_ca.paa";
        icon = "\HS_UI_FN\Map\Markers\Flags\scp_ca.paa";
        priority = 2;
    };
};

class CfgGroups {
    class WEST {

        class HS_SCP_Fac {
            name = "SCP Foundation";

            class Infantry {
                name = "Infantry";

                class b_hsscpfac_infantry_security_team {
                    name = "Security Team";
                    side = 1;
                    faction = "hs_scp_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSSCPFac_Security_Guard_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Security_Guard_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Security_Guard_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Security_Guard_01";
                    };
                };

                class b_hsscpfac_infantry_heavy_security_team {
                    name = "Heavy Security Team";
                    side = 1;
                    faction = "hs_scp_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSSCPFac_Security_Guard_Heavy_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Security_Guard_Heavy_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Security_Guard_Heavy_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Security_Guard_Heavy_01";
                    };
                };

                class b_hsscpfac_infantry_containment_specialist_squad {
                    name = "Containment Specialist Squad";
                    side = 1;
                    faction = "hs_scp_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSSCPFac_Containment_Specialist_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Containment_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Containment_Specialist_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Containment_Specialist_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Containment_Specialist_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Containment_Specialist_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Containment_Specialist_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Containment_Specialist_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

                class b_hsscpfac_specops_mtf_squad {
                    name = "MTF Squad";
                    side = 1;
                    faction = "HS_SCP_Fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_UAV_Operator_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Gunner_01";
                    };
                };

                class b_hsscpfac_specops_mtf_fireteam {
                    name = "MTF Fireteam";
                    side = 1;
                    faction = "HS_SCP_Fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_01";
                    };
                    class Unit3 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Autorifleman_01";
                    };
                };

                class b_hsscpfac_specops_trt_squad {
                    name = "TRT Squad";
                    side = 1;
                    faction = "HS_SCP_Fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSSCPFac_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Medic_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Gunner_02";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                };

                class b_hsscpfac_specops_trt_fireteam {
                    name = "TRT Fireteam";
                    side = 1;
                    faction = "HS_SCP_Fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSSCPFac_Operator_02";
                    };
                };

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_Soldier_F;
    class B_Soldier_F_OCimport_01 : B_Soldier_F { scope = 0; class EventHandlers; };
    class B_Soldier_F_OCimport_02 : B_Soldier_F_OCimport_01 { class EventHandlers; };

    class B_diver_F;
    class B_diver_F_OCimport_01 : B_diver_F { scope = 0; class EventHandlers; };
    class B_diver_F_OCimport_02 : B_diver_F_OCimport_01 { class EventHandlers; };

    class B_Patrol_Soldier_TL_F;
    class B_Patrol_Soldier_TL_F_OCimport_01 : B_Patrol_Soldier_TL_F { scope = 0; class EventHandlers; };
    class B_Patrol_Soldier_TL_F_OCimport_02 : B_Patrol_Soldier_TL_F_OCimport_01 { class EventHandlers; };

    class B_HSSCPFac_Security_Guard_01 : B_Soldier_F_OCimport_02 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Security Guard";
        side = 1;
        faction = "hs_scp_fac";
        editorSubcategory="HS_SCP_SECURITY";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Fatigues";

        linkedItems[] = {"HS_Modular_Carrier_M_B","MLO_Helmet2","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_M_B","MLO_Helmet2","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"SMG_03C_black","hgun_P07_blk_F"};
        respawnWeapons[] = {"SMG_03C_black","hgun_P07_blk_F"};

        magazines[] = {"50Rnd_570x28_SMG_03","16Rnd_9x21_Mag","50Rnd_570x28_SMG_03","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"50Rnd_570x28_SMG_03","16Rnd_9x21_Mag","50Rnd_570x28_SMG_03","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"SMG_03C_black","","","",{"50Rnd_570x28_SMG_03",50},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Fatigues",{{"FirstAidKit",2}}},{"HS_Modular_Carrier_M_B",{{"SCP_CB_Things_Keycard_C2",1},{"16Rnd_9x21_Mag",3,16},{"50Rnd_570x28_SMG_03",8,50}}},{},"MLO_Helmet2","HS_Balaclava_B",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Security_Guard_Light_01 : B_HSSCPFac_Security_Guard_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Security Guard [Light]";
        side = 1;
        faction = "hs_scp_fac";
        editorSubcategory="HS_SCP_SECURITY";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Uniform_SCP_F";

        linkedItems[] = {"HS_Security_Belt_SCP","HS_Cap_SCP","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"HS_Security_Belt_SCP","HS_Cap_SCP","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"hgun_P07_blk_F"};
        respawnWeapons[] = {"hgun_P07_blk_F"};

        magazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Uniform_SCP_F",{{"FirstAidKit",2}}},{"HS_Security_Belt_SCP",{{"SCP_CB_Things_Keycard_C2",1},{"30Rnd_9x21_Mag",4,30}}},{},"HS_Cap_SCP","G_Tactical_Clear",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Security_Guard_Heavy_01 : B_HSSCPFac_Security_Guard_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Security Guard [Heavy]";
        side = 1;
        faction = "hs_scp_fac";
        editorSubcategory="HS_SCP_SECURITY";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Fatigues_RS";

        linkedItems[] = {"HS_Modular_Carrier_H_B","MLO_Helmet2","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_H_B","MLO_Helmet2","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"SMG_03C_black","hgun_P07_blk_F"};
        respawnWeapons[] = {"SMG_03C_black","hgun_P07_blk_F"};

        magazines[] = {"50Rnd_570x28_SMG_03","16Rnd_9x21_Mag","50Rnd_570x28_SMG_03","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"50Rnd_570x28_SMG_03","16Rnd_9x21_Mag","50Rnd_570x28_SMG_03","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"SMG_03C_black","","","",{"50Rnd_570x28_SMG_03",50},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Fatigues_RS",{{"FirstAidKit",2}}},{"HS_Modular_Carrier_H_B",{{"SCP_CB_Things_Keycard_C2",1},{"16Rnd_9x21_Mag",3,16},{"50Rnd_570x28_SMG_03",9,50}}},{},"MLO_Helmet2","HS_Balaclava_B",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Security_Officer_01 : B_HSSCPFac_Security_Guard_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Security Officer";
        side = 1;
        faction = "hs_scp_fac";
        editorSubcategory="HS_SCP_SECURITY";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Officer_Uniform_SCP_F";

        linkedItems[] = {"HS_TacVest_SCP","HS_Patrol_Cap_SCP","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"HS_TacVest_SCP","HS_Patrol_Cap_SCP","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"hgun_P07_blk_F"};
        respawnWeapons[] = {"hgun_P07_blk_F"};

        magazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Officer_Uniform_SCP_F",{{"FirstAidKit",2}}},{"HS_TacVest_SCP",{{"SCP_CB_Things_Keycard_C3",1},{"30Rnd_9x21_Mag",4,30}}},{},"HS_Patrol_Cap_SCP","G_Tactical_Clear",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Pilot_01 : B_HSSCPFac_Security_Guard_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 1;
        faction = "hs_scp_fac";
        editorSubcategory="HS_SCP_PERS";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Officer_Uniform_SCP_F";

        linkedItems[] = {"HS_TacVest_SCP","H_PilotHelmetHeli_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"HS_TacVest_SCP","H_PilotHelmetHeli_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"hgun_P07_blk_F"};
        respawnWeapons[] = {"hgun_P07_blk_F"};

        magazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Officer_Uniform_SCP_F",{{"FirstAidKit",2},{"SmokeShellBlue",2,1},{"SmokeShellPurple",2,1},{"SmokeShellRed",2,1},{"SmokeShell",2,1}}},{"HS_TacVest_SCP",{{"SCP_CB_Things_Keycard_C2",1},{"30Rnd_9x21_Mag",4,30}}},{},"H_PilotHelmetHeli_B","G_WirelessEarpiece_F",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Helicopter_Crewman_01 : B_HSSCPFac_Pilot_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Helicopter Crewman";
        side = 1;
        faction = "hs_scp_fac";
        editorSubcategory="HS_SCP_PERS";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Combat_Fatigues_RS";

        linkedItems[] = {"HS_TacVest_SCP","H_CrewHelmetHeli_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"HS_TacVest_SCP","H_CrewHelmetHeli_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"hgun_P07_blk_F"};
        respawnWeapons[] = {"hgun_P07_blk_F"};

        magazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Combat_Fatigues_RS",{{"FirstAidKit",2},{"SmokeShellBlue",2,1},{"SmokeShellPurple",2,1},{"SmokeShellRed",2,1},{"SmokeShell",2,1}}},{"HS_TacVest_SCP",{{"SCP_CB_Things_Keycard_C2",1},{"30Rnd_9x21_Mag",4,30}}},{},"H_CrewHelmetHeli_B","G_WirelessEarpiece_F",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Containment_Specialist_01 : B_HSSCPFac_Security_Guard_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Containment Specialist";
        side = 1;
        faction = "hs_scp_fac";
        editorSubcategory="HS_SCP_CONTAINMENT";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_CBRN_SCP_W";

        linkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_Basic_Helmet_Black","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_Basic_Helmet_Black","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F"};

        weapons[] = {"arifle_MX_Black_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_MX_Black_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag"};

        backpack = "B_SCBA_01_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MX_Black_F","","acc_flashlight","optic_Holosight_blk_F",{"30Rnd_65x39_caseless_black_mag",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_CBRN_SCP_W",{{"FirstAidKit",4}}},{"HS_Modular_Carrier_Lite_B",{{"SCP_CB_Things_Keycard_C2",1},{"30Rnd_65x39_caseless_black_mag",9,30},{"16Rnd_9x21_Mag",3,16},{"SmokeShell",2,1}}},{"B_SCBA_01_F",{}},"HS_Basic_Helmet_Black","G_AirPurifyingRespirator_01_F",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Containment_Technician_01 : B_HSSCPFac_Containment_Specialist_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Containment Technician";
        side = 1;
        faction = "hs_scp_fac";
        editorSubcategory="HS_SCP_CONTAINMENT";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Officer_Uniform_SCP_F";

        linkedItems[] = {"HS_TacVest_SCP","HS_Cap_SCP"};
        respawnlinkedItems[] = {"HS_TacVest_SCP","HS_Cap_SCP"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"HS_Security_Officer_Uniform_SCP_F",{}},{"HS_TacVest_SCP",{{"16Rnd_9x21_Mag",3,16}}},{},"HS_Cap_SCP","G_WirelessEarpiece_F",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Operator_01 : B_diver_F_OCimport_02 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Operator";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_MTF";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_diver"};

        uniformClass = "HS_Combat_Fatigues_B";

        linkedItems[] = {"HS_FAPC_Operator","HS_AMH_Headset_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_FAPC_Operator","HS_AMH_Headset_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"arifle_SPAR_01_blk_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_SPAR_01_blk_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_SPAR_01_blk_F","muzzle_snds_M","acc_pointer_IR","optic_Holosight_blk_F",{"30Rnd_556x45_Stanag",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Combat_Fatigues_B",{{"SCP_CB_Things_Keycard_C3",1}}},{"HS_FAPC_Operator",{{"FirstAidKit",5},{"30Rnd_556x45_Stanag",9,30},{"30Rnd_9x21_Mag",3,30},{"HandGrenade",2,1},{"SmokeShell",2,1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",1,1}}},{},"HS_AMH_Headset_B","VSM_balaclava2_Black",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Autorifleman_01 : B_HSSCPFac_Operator_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_MTF";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_diver"};

        uniformClass = "HS_Combat_Fatigues_B";

        linkedItems[] = {"HS_FAPC_MG","HS_AMH_Headset_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_FAPC_MG","HS_AMH_Headset_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"arifle_SPAR_02_blk_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_SPAR_02_blk_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"150Rnd_556x45_Drum_Mag_F","16Rnd_9x21_Mag","150Rnd_556x45_Drum_Mag_F","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"150Rnd_556x45_Drum_Mag_F","16Rnd_9x21_Mag","150Rnd_556x45_Drum_Mag_F","16Rnd_9x21_Mag"};

        backpack = "HS_shoulder_bag_SCP";

        ALiVE_orbatCreator_loadout[] = {{"arifle_SPAR_02_blk_F","muzzle_snds_M","acc_pointer_IR","optic_ERCO_blk_F",{"150Rnd_556x45_Drum_Mag_F",150},{},"bipod_01_F_blk"},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Combat_Fatigues_B",{{"SCP_CB_Things_Keycard_C3",1}}},{"HS_FAPC_MG",{{"30Rnd_9x21_Mag",3,30},{"HandGrenade",2,1},{"SmokeShell",2,1},{"150Rnd_556x45_Drum_Mag_F",8,150}}},{"HS_shoulder_bag_SCP",{{"FirstAidKit",5},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",2,1}}},"HS_AMH_Headset_B","VSM_balaclava_Black",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Medic_01 : B_HSSCPFac_Operator_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_MTF";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_diver"};

        uniformClass = "HS_Combat_Fatigues_B_RS";

        linkedItems[] = {"HS_FAPC_Operator","HS_AMH_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_FAPC_Operator","HS_AMH_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"SMG_05_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"SMG_05_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag","30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag","30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag"};

        backpack = "HS_Kitbag_B";

        ALiVE_orbatCreator_loadout[] = {{"SMG_05_F","muzzle_snds_L","acc_pointer_IR","optic_ACO_grn",{"30Rnd_9x21_Mag_SMG_02",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Combat_Fatigues_B_RS",{{"SCP_CB_Things_Keycard_C3",1}}},{"HS_FAPC_Operator",{{"30Rnd_9x21_Mag",3,30},{"HandGrenade",2,1},{"SmokeShell",2,1},{"30Rnd_9x21_Mag_SMG_02",9,30}}},{"HS_Kitbag_B",{{"FirstAidKit",15},{"Medikit",1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",2,1}}},"HS_AMH_B","VSM_balaclava2_Black",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Marksman_01 : B_HSSCPFac_Operator_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_MTF";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_diver"};

        uniformClass = "HS_Combat_Fatigues_B";

        linkedItems[] = {"HS_FAPC_Operator","HS_Cap_SCP","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_FAPC_Operator","HS_Cap_SCP","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"arifle_SPAR_03_blk_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_SPAR_03_blk_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"20Rnd_762x51_Mag","16Rnd_9x21_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"20Rnd_762x51_Mag","16Rnd_9x21_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag"};

        backpack = "HS_Compact_Bag_B";

        ALiVE_orbatCreator_loadout[] = {{"arifle_SPAR_03_blk_F","muzzle_snds_B","acc_pointer_IR","optic_DMS",{"20Rnd_762x51_Mag",20},{},"bipod_01_F_blk"},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Combat_Fatigues_B",{{"SCP_CB_Things_Keycard_C3",1},{"20Rnd_762x51_Mag",2,20}}},{"HS_FAPC_Operator",{{"30Rnd_9x21_Mag",3,30},{"HandGrenade",2,1},{"SmokeShell",2,1},{"20Rnd_762x51_Mag",9,20}}},{"HS_Compact_Bag_B",{{"FirstAidKit",5},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",2,1}}},"HS_Cap_SCP","VSM_Balaclava_black_Peltor_Goggles",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Gunner_01 : B_HSSCPFac_Operator_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Gunner";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_MTF";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_diver"};

        uniformClass = "HS_Combat_Fatigues_B_RS";

        linkedItems[] = {"HS_Modular_Carrier_Vest_Heavy_B","HS_AMH_Chops_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_Vest_Heavy_B","HS_AMH_Chops_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"LMG_03_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"LMG_03_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"200Rnd_556x45_Box_F","16Rnd_9x21_Mag","200Rnd_556x45_Box_F","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"200Rnd_556x45_Box_F","16Rnd_9x21_Mag","200Rnd_556x45_Box_F","16Rnd_9x21_Mag"};

        backpack = "HS_Kitbag_B";

        ALiVE_orbatCreator_loadout[] = {{"LMG_03_F","","acc_pointer_IR","optic_Holosight_blk_F",{"200Rnd_556x45_Box_F",200},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Combat_Fatigues_B_RS",{{"SCP_CB_Things_Keycard_C3",1}}},{"HS_Modular_Carrier_Vest_Heavy_B",{{"30Rnd_9x21_Mag",5,30},{"HandGrenade",2,1},{"SmokeShell",2,1}}},{"HS_Kitbag_B",{{"FirstAidKit",5},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",2,1},{"200Rnd_556x45_Box_F",4,200},{"200Rnd_556x45_Box_Tracer_F",1,200}}},"HS_AMH_Chops_B","VSM_Balaclava2_black_Goggles",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_UAV_Operator_01 : B_HSSCPFac_Operator_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAV Operator";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_MTF";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_diver"};

        uniformClass = "HS_Combat_Fatigues_B";

        linkedItems[] = {"HS_FAPC_Operator","HS_AMH_B","ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_FAPC_Operator","HS_AMH_B","ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"arifle_SPAR_01_blk_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_SPAR_01_blk_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};

        backpack = "HS_UAV_backpack_SCP";

        ALiVE_orbatCreator_loadout[] = {{"arifle_SPAR_01_blk_F","muzzle_snds_M","acc_pointer_IR","optic_Holosight_blk_F",{"30Rnd_556x45_Stanag",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Combat_Fatigues_B",{{"SCP_CB_Things_Keycard_C3",1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",1,1}}},{"HS_FAPC_Operator",{{"FirstAidKit",5},{"30Rnd_556x45_Stanag",9,30},{"30Rnd_9x21_Mag",3,30},{"HandGrenade",2,1},{"SmokeShell",2,1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",1,1}}},{"HS_UAV_backpack_SCP",{}},"HS_AMH_B","VSM_Balaclava_black_Peltor_glasses",{"Binocular","","","",{},{},""},{"ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_CBRN_Specialist_01 : B_HSSCPFac_Operator_01 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "CBRN Specialist";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_MTF";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_diver"};

        uniformClass = "HS_CBRN_SCP_B";

        linkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_ECH_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_ECH_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"arifle_SPAR_01_blk_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_SPAR_01_blk_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_SPAR_01_blk_F","muzzle_snds_M","acc_pointer_IR","optic_Holosight_blk_F",{"30Rnd_556x45_Stanag",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_CBRN_SCP_B",{{"SCP_CB_Things_Keycard_C3",1},{"FirstAidKit",1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",1,1}}},{"HS_Modular_Carrier_Lite_B",{{"30Rnd_556x45_Stanag",9,30},{"30Rnd_9x21_Mag",3,30},{"HandGrenade",2,1},{"SmokeShell",2,1}}},{"B_CombinationUnitRespirator_01_F",{{"FirstAidKit",2}}},"HS_ECH_B","HS_M40_Hood_B",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Operator_02 : B_Patrol_Soldier_TL_F_OCimport_02 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Operator";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_TRT";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Fatigues";

        linkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_AMH_Headset_W","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_AMH_Headset_W","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};

        weapons[] = {"arifle_MX_Black_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_MX_Black_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag"};

        backpack = "HS_shoulder_bag_SCP";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MX_Black_F","","acc_flashlight","optic_Holosight_blk_F",{"30Rnd_65x39_caseless_black_mag",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Fatigues",{{"FirstAidKit",4}}},{"HS_Modular_Carrier_Lite_B",{{"SCP_CB_Things_Keycard_C3",1},{"30Rnd_65x39_caseless_black_mag",9,30},{"16Rnd_9x21_Mag",3,16},{"SmokeShell",2,1}}},{"HS_shoulder_bag_SCP",{}},"HS_AMH_Headset_W","VSM_balaclava2_Black",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Gunner_02 : B_HSSCPFac_Operator_02 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Gunner";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_TRT";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Fatigues";

        linkedItems[] = {"HS_Modular_Carrier_Vest_Heavy_B","HS_AMH_Chops_W","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_Vest_Heavy_B","HS_AMH_Chops_W","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};

        weapons[] = {"LMG_Mk200_black_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"LMG_Mk200_black_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"200Rnd_65x39_cased_Box","16Rnd_9x21_Mag","200Rnd_65x39_cased_Box","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"200Rnd_65x39_cased_Box","16Rnd_9x21_Mag","200Rnd_65x39_cased_Box","16Rnd_9x21_Mag"};

        backpack = "HS_Kitbag_B";

        ALiVE_orbatCreator_loadout[] = {{"LMG_Mk200_black_F","","acc_flashlight","optic_Holosight_blk_F",{"200Rnd_65x39_cased_Box",200},{},"bipod_01_F_blk"},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Fatigues",{{"FirstAidKit",4}}},{"HS_Modular_Carrier_Vest_Heavy_B",{{"SCP_CB_Things_Keycard_C3",1},{"16Rnd_9x21_Mag",5,16},{"SmokeShell",2,1},{"HandGrenade",2,1}}},{"HS_Kitbag_B",{{"200Rnd_65x39_cased_Box",3,200},{"200Rnd_65x39_cased_Box_Tracer",2,200}}},"HS_AMH_Chops_W","VSM_Balaclava_black_Goggles",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Medic_02 : B_HSSCPFac_Operator_02 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_TRT";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Fatigues";

        linkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_AMH_W","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_AMH_W","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"SMG_05_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"SMG_05_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag","30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag","30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag"};

        backpack = "HS_Kitbag_B";

        ALiVE_orbatCreator_loadout[] = {{"SMG_05_F","muzzle_snds_L","acc_pointer_IR","optic_ACO_grn",{"30Rnd_9x21_Mag_SMG_02",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Fatigues",{{"SCP_CB_Things_Keycard_C3",1}}},{"HS_Modular_Carrier_Lite_B",{{"30Rnd_9x21_Mag",3,30},{"HandGrenade",2,1},{"SmokeShell",2,1},{"30Rnd_9x21_Mag_SMG_02",7,30}}},{"HS_Kitbag_B",{{"FirstAidKit",15},{"Medikit",1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1},{"B_IR_Grenade",2,1}}},"HS_AMH_W","VSM_balaclava2_Black",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSSCPFac_Squad_Leader_01 : B_HSSCPFac_Operator_02 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 1;
        faction = "HS_SCP_Fac";
        editorSubcategory="HS_SCP_TRT";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_Security_Fatigues";

        linkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_AMH_Headset_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"HS_Modular_Carrier_Lite_B","HS_AMH_Headset_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"};

        weapons[] = {"arifle_MX_Black_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_MX_Black_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_black_mag","16Rnd_9x21_Mag"};

        backpack = "HS_shoulder_bag_SCP";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MX_Black_F","","acc_flashlight","optic_Holosight_blk_F",{"30Rnd_65x39_caseless_black_mag",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_Security_Fatigues",{{"FirstAidKit",4}}},{"HS_Modular_Carrier_Lite_B",{{"SCP_CB_Things_Keycard_C3",1},{"30Rnd_65x39_caseless_black_mag",9,30},{"16Rnd_9x21_Mag",3,16},{"SmokeShell",2,1}}},{"HS_shoulder_bag_SCP",{}},"HS_AMH_Headset_B","VSM_balaclava2_Black",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ChemicalDetector_01_watch_F","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};