//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 210.149954 on Stable branch
// Generated with ALiVE version 1.17.0.2209061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class HS_GOC_Fac {
        displayName = "Global Occult Coalition ";
        side = 1;
        flag = "\HS_UI_FN\Map\Markers\Flags\goc_ca.paa";
        icon = "\HS_UI_FN\Map\Markers\Flags\goc_ca.paa";
        priority = 2;
    };
};

class CfgGroups {
    class WEST {

        class HS_GOC_Fac {
            name = "Global Occult Coalition ";

            class Infantry {
                name = "Infantry";

                class b_hsgocfac_infantry_fireteam_cbrn {
                    name = "Fireteam (CBRN)";
                    side = 1;
                    faction = "hs_goc_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                };

                class b_hsgocfac_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "hs_goc_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                };

                class b_hsgocfac_infantry_squad {
                    name = "Squad";
                    side = 1;
                    faction = "hs_goc_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_01";
                    };
                };

                class b_hsgocfac_infantry_squad_cbrn {
                    name = "Squad (CBRN)";
                    side = 1;
                    faction = "hs_goc_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_HSGOCFac_Operator_CBRN_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class HS_FND_APC_Base;
    class HS_FND_APC_Base_OCimport_01 : HS_FND_APC_Base { scope = 0; class EventHandlers; class Turrets; };
    class HS_FND_APC_Base_OCimport_02 : HS_FND_APC_Base_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class HS_FND_IFV_Base;
    class HS_FND_IFV_Base_OCimport_01 : HS_FND_IFV_Base { scope = 0; class EventHandlers; class Turrets; };
    class HS_FND_IFV_Base_OCimport_02 : HS_FND_IFV_Base_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class B_HSGOCFac_Operator_CBRN_01;
    class B_HSGOCFac_Operator_CBRN_01_OCimport_01 : B_HSGOCFac_Operator_CBRN_01 { scope = 0; class EventHandlers; };
    class B_HSGOCFac_Operator_CBRN_01_OCimport_02 : B_HSGOCFac_Operator_CBRN_01_OCimport_01 { class EventHandlers; };

    class B_HSGOCFac_Rifleman_01 : B_HSGOCFac_Operator_CBRN_01_OCimport_02 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "hs_goc_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "HS_GOC_Fatigues";

        linkedItems[] = {"HS_Carrier_Lite_B","HS_Basic_Helmet_Blue_GOC","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"HS_Carrier_Lite_B","HS_Basic_Helmet_Blue_GOC","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"arifle_MSBS65_black_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_black_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_black_F","","","optic_Holosight_blk_F",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"HS_GOC_Fatigues",{{"FirstAidKit",3},{"16Rnd_9x21_Mag",1,16}}},{"HS_Carrier_Lite_B",{{"16Rnd_9x21_Mag",3,16},{"30Rnd_65x39_caseless_msbs_mag",7,30},{"HandGrenade",1,1},{"SmokeShell",2,1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",1,1}}},{},"HS_Basic_Helmet_Blue_GOC","VSM_balaclava2_Black",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_HSGOCFac_CBRN_Specialist_01 : B_HSGOCFac_Operator_CBRN_01_OCimport_02 {
        author = "Schlopp";
        scope = 2;
        scopeCurator = 2;
        displayName = "CBRN Specialist";
        side = 1;
        faction = "hs_goc_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"V_PlateCarrier2_blk","HS_Basic_Helmet_Blue_GOC","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","HS_Basic_Helmet_Blue_GOC","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"arifle_MSBS65_black_F","hgun_P07_blk_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_black_F","hgun_P07_blk_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_black_F","","","optic_Holosight_blk_F",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_P07_blk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"16Rnd_9x21_Mag",1,16}}},{"V_PlateCarrier2_blk",{{"16Rnd_9x21_Mag",3,16},{"30Rnd_65x39_caseless_msbs_mag",8,30},{"HandGrenade",1,1},{"SmokeShell",2,1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"Chemlight_red",2,1},{"Chemlight_yellow",2,1}}},{"B_CombinationUnitRespirator_01_F",{}},"HS_Basic_Helmet_Blue_GOC","HS_M40_Hood_B",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};